#!/bin/bash
. "$HOME/.scripts/dmenu/root"

CHOICE=$(printf '%s\n' "Shutdown" "Reboot" "Suspend" | dm -p "Operation: ")

case "$CHOICE" in
	Shutdown)  /sbin/shutdown now ;;
	Reboot) /sbin/rebooot ;;
	Suspend) systemctl suspend;;
esac