#!/bin/bash
. "$HOME/.scripts/dmenu/root"


selected="$(ps -a -u "$USER" | \
            dm -i -p "Type to search and select process to kill" | \
            awk '{print $1" "$4}')"; 

if [[ ! -z $selected ]]; then

    answer="$(echo -e "Yes\nNo" | \
            dm -i -p "$selected will be killed, are you sure?" \
            )"

    if [[ $answer == "Yes" ]]; then
        selpid="$(awk '{print $1}' <<< $selected)"; 
        kill -9 $selpid
    fi
fi


exit 0
