#!/bin/bash

external_monitor="HDMI-1"
brightness=$(echo "" | dmenu)


if [[ -n $brightness ]]; then
    xrandr --output "$external_monitor" --brightness "$brightness"    
else 
	notify-send "Please enter a brightness value between 0 and 1 🚀"
fi
echo "$brightness"
