#!/usr/bin/bash

script_path="$HOME/.scripts/dmenu"
. "$script_path/root"

prompt="-p Menus:"

# list only executable non-binary files

selected_script="$(find $script_path/dmenu-* -maxdepth 1 -type f -executable \
          -exec grep -Iq . {} \; -print \
          | sed 's|^'$script_path/'||' \
          | sed 's|^'dmenu-'||' \
          | sort \
          | dm $prompt)"

if [ -z $selected_script ]; then
    notify-send "ABORTING! No operation selected"
    exit 0
fi

eval "$script_path/dmenu-$selected_script"

exit 0